name: GitHub Actions Trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push action notification
        run: |
          echo "Push or Pull Request event triggered"