name: GitHub Actions Trigger

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  webhook_event:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

#asd